services:
  zip_xtractor:
    image: zip_xtractor:dev
    container_name: zip_xtractor
    user: 1000:1000
    command: tail -f /dev/null # keep alive infinite loop
    volumes:
      - /home/xliuk/repos/zip_xtractor/sourceDir:/app/sourceDir
      - /home/xliuk/repos/zip_xtractor/outputDir:/app/outputDir
    environment:
      WATCH_DIR: "/app/sourceDir"
      TARGET_DIR: "/app/outputDir"
      DEBOUNCE_TIME: "3"
